---
title: "Leporid brains"
output: html_document
---


#Loading packages
```{r load packages}

require(caper)
require(car)
require(plotly)
require(ggplot2)
library(MCMCglmm)
library(mulTree)
require(phytools)
require(forcats)
require(bayesplot)
library(hdrcde)
require(mice)
require(phylomice)
````


#Loading data and tree
```{r load data and tree}

lep.data <-read.table("./Data/lepdata_trimmed2.txt", sep = "\t", header = TRUE)
lep.tree <-read.tree("./Data/leptree.txt")

#convert var types

lep.data$DietBreadth <- as.numeric(lep.data$DietBreadth)
lep.data$Burrow < as.numeric(lep.data$DietBurrow)


lep.data$ECV_T <- log(lep.data$ECV_T)
lep.data$ECV_OB <- log(lep.data$ECV_OB)
lep.data$ECV_ROB <- log(lep.data$ECV_ROB)

lep.data$AdultBodyMass <- log(lep.data$AdultBodyMass)
lep.data$GestationLen <- log(lep.data$GestationLen)
lep.data$HomeRange <- log(lep.data$HomeRange)
lep.data$LitterSize <- log(lep.data$LitterSize)
lep.data$GR_Area <- log(lep.data$GR_Area)

#set row names and check for missingness
rownames(lep.data) <- lep.data$Name_phyl
clean.data(lep.data, lep.tree)  ## check if data == tree names

```



#imputation
```{r mice}
data_mice <- lep.data

library(VIM)
aggr_plot <- aggr(data_mice, col=c('navyblue','red'), numbers=TRUE, sortVars=TRUE, labels=names(data_mice), cex.axis=.7, gap=3, ylab=c("Histogram of missing data","Pattern"))

prec <- precomputePsi(lep.tree)

imp <- mice(data_mice, m=5, meth = "phpmm", psi = prec$psi, psiinv = prec$psiinv, maxit = 2)

pred <- imp$predictorMatrix
pred[, "Name_phyl"] <- 0
pred[, "Se_temp"] <- 0
pred[, "Se_precip"] <- 0
pred[, "ST"] <- 0
pred[, "SP"] <- 0

imp <- mice(data_mice, m=5, pred = pred meth = "phpmm", psi = prec$psi, psiinv = prec$psiinv, maxit = 2)


```

#doctoring the tree
```{r fixing the tree, message=FALSE, warning=FALSE}
lep.tree$edge.length[which(lep.tree$edge.length == 0)] <- 0.01*median(lep.tree$edge.length[-which(lep.tree$edge.length == 0)])
lep.tree <- force.ultrametric(lep.tree,method="extend")
```



Formulas
```{r formulas}
formula1 <- ECV_T ~ SeT * SeP * AdultBodyMass
formula2 <- ECV_OB ~ SeT * SeP * AdultBodyMass
formula3 <- ECV_ROB ~ SeT * SeP * AdultBodyMass


formula1a <- ECV_T ~ SeT * SeP * Burrow * Locomotor_Mode * Activity * AdultBodyMass
formula2a <- ECV_OB ~ SeT * SeP * Burrow * Locomotor_Mode * Activity * AdultBodyMass
formula3a <- ECV_ROB ~ SeT * SeP * Burrow * Locomotor_Mode * Activity * AdultBodyMass

formula1b <- ECV_T ~ SeT * SeP * DietBreadth * GR_Area * AdultBodyMass
formula2b <- ECV_OB ~ SeT * SeP * DietBreadth * GR_Area * AdultBodyMass
formula3b <- ECV_ROB ~ SeT * SeP * DietBreadth * GR_Area * AdultBodyMass

formula1c <- ECV_T ~ SeT * SeP * GestationLen * LitterSize * AdultBodyMass
formula2c <- ECV_OB ~ SeT * SeP * GestationLen * LitterSize * AdultBodyMass
formula3c <- ECV_ROB ~ SeT * SeP * GestationLen * LitterSize * AdultBodyMass

```


#Parameters for the MCMC
```{r parameters, message=FALSE, warning=FALSE}
# Number of interations
nitt <- 250000
# Length of burnin -> what to ignore (the initial N ot iterations)
burnin <- 30000
# Amount of thinning -> lenght of step (sampling rate)
thin <- 101
```


#Creating mulTree objects
```{r multree, message=FALSE, warning=FALSE, verbose = FALSE}

mulTree_data <- as.mulTree(data = lep.data, tree = lep.tree,
                           taxa = "Name_phyl")
```

#change formulas
```{r multree, message=FALSE, warning=FALSE}
# The formula
mul_formula <- formula2
# The MCMC parameters (iterations, thining, burnin)
mul_parameters <- c(nitt, thin, burnin)
# The MCMCglmm priors
mul_priors <- list(R = list(V = 1, nu = 0.002),
                   G = list(G1 = list(V = 1, nu = 0.002)))
```

```{r running multree, message=FALSE, warning=FALSE}
mulTree(mulTree.data = mulTree_data, formula = mul_formula, priors = mul_priors,
        parameters = mul_parameters, output = "./MCMCmodels/model1", ESS = 1000,
        chains = 2)
```


```{r plotting the densities }

setwd("./MCMCmodels")

one_model1 <- read.mulTree("model1-tree1_chain1", model = TRUE)
solX <- as.matrix(one_model1$Sol)
res.plot <- as.data.frame(one_model1$Sol)

setwd("./")

names <- colnames(solX)
colnames(solX) <- names
solX <- as.data.frame(solX)

sum <- as.mcmc(one_model1$Sol)
sum <- summary(sum)
sum <- as.data.frame(sum$statistics)

```

```{r}
#plot in a pdf
library(hdrcde)

pdf(file="./MCMCmodels/density.pdf")
par( mfrow = c( 3, 3 ))
    for(column in 1:8) {
    percentage_above_zero <- length(which(solX[,column] >= 0))/length(solX[,column])
hdr.den(solX[,column], main = names(solX[column]), sub = paste0(round(percentage_above_zero*100,2), "% above zero"))
abline(v = 0, lty = 1)  
    }

color_scheme_set("brightblue")
mcmc_intervals(res.plot)


p <- ggplot(
    sum, 
    aes(x = Mean, y = fct_rev(row.names(sum)), xmin = Mean-SD, xmax = Mean+SD)) +
    geom_point(aes(color = row.names(sum))) +
    geom_errorbarh(aes(color = row.names(sum)), height=0.05)+
    geom_vline(xintercept = 0, color = "red", linetype="longdash", size=0.5) +
    theme_light()
p$labels$colour <- "Model"
p$labels$x <- "Posterior estimate + SD"
p$labels$y <- "Model parameters"
p

dev.off()


solX <- as.mcmc(one_model1$Sol)
sum <- summary(solX)
sum <- as.data.frame(sum$statistics)

write.table(sum, "./MCMCmodels/analysis-output.csv", sep = ",", col.names = TRUE, row.names = TRUE)

```











#Old PGLSs
```{r old pgsl}

leporid <- comparative.data(phy = leptree, data = lepdata, names.col = Name_phyl, vcv = TRUE, na.omit = FALSE, warn.dropped = TRUE)

#obtain residuals

#for total brain/body
model.pgls.res <- pgls(log(ECV_T) ~ log(AdultBodyMass), data = leporid, lambda='ML')
res <- model.pgls.res$res

#for OB rel to T
model.pgls.res.ob <- pgls(log(ECV_OB) ~ log(ECV_T), data = leporid, lambda='ML')
res.ob <- model.pgls.res.ob$res


#models

model.Se1<-pgls(log(ECV_OB) ~ log(SeT)*log(AdultBodyMass), data = leporid, lambda='ML')
summary(model.Se1) # oB but not ROB or T (both absolute and relative work here!)


model.Se2<-pgls(res.ob ~ log(SeP), data = leporid, lambda='ML')
summary(model.Se2)


model.GR<-pgls(log(ECV_T) ~ (log(GR_Area))*log(AdultBodyMass), data = leporid, lambda='ML')
summary(model.GR) # T and ROB but not OB or relative OB (Home Range NS) - I think nothing from here


#plot
ggplot(lepdata, aes(x = res.ob, y = log(SeP))) + geom_point()

       #or
p <- plot_ly(lepdata, x = ~log(ECV_OB)/log(ECV_T), y = ~log(SeT), z = ~log(AdultBodyMass), color = ~Activity, colors = c('#BF382A', '#0C4B8E')) %>%
  add_markers() %>%
  layout(scene = list(xaxis = list(title = 'RelBrain'),
                      yaxis = list(title = 'SeT'),
                      zaxis = list(title = 'BodyMass')))




#Check for vifs

DataCA=data.frame(res.ob, lepdata$SeT, lepdata$SeP, lepdata$AdultBodyMass)
Lm_CA=lm(res.ob ~ lepdata.SeP*lepdata.AdultBodyMass, data=DataCA)
vif(Lm_CA) # low vifs


cor.test(lepdata$SeT, lepdata$SeP) #low cross correlation between SeT & SeP

```
